DROP TABLE IF EXISTS users, films, genres, ratings, friendship, film_genre, likes, DIRECTORS, DIRECTORS_FILMS,
                     reviews, reviews_ratings CASCADE;

CREATE TABLE if not exists DIRECTORS (
      director_id INTEGER not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name_director varchar(255) not null
  );

CREATE TABLE IF NOT EXISTS genre
(
    genre_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_genre   VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ratings
(
    rating_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_rating  VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users
(
    user_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email 		 VARCHAR(255) NOT NULL,
    login        VARCHAR (255) NOT NULL,
    name  		 VARCHAR(255),
    birthday 	 DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name		 VARCHAR(255) NOT NULL,
    description  VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration 	 INT NOT NULL,
    rating_id	 INT NOT NULL REFERENCES ratings(rating_id),
    rate  INT
);

CREATE TABLE IF NOT EXISTS reviews
(
    review_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content      VARCHAR(255) NOT NULL,
    is_positive  BOOLEAN NOT NULL,
    user_id      INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    film_id      INT NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    useful       INT
);

CREATE TABLE IF NOT EXISTS reviews_ratings
(
    review_id    INT NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id      INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    rate         INT,
    PRIMARY KEY (review_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id      INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    friend_id 	 INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id     INT REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id    INT REFERENCES genre (genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS popular_films (
    film_id     BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
    user_id     BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)

);

CREATE TABLE if not exists DIRECTORS_FILMS (
    director_id int not null references DIRECTORS(director_id) ON DELETE CASCADE,
    film_id  int not null references FILMS(film_id) ON DELETE CASCADE,

    PRIMARY KEY(director_id,film_id)
);
