DROP TABLE IF EXISTS users, films, genres, ratings, friendship, film_genre, likes CASCADE;

CREATE TABLE IF NOT EXISTS genre
(
    genre_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_genre   VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ratings
(
    rating_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_rating  VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users
(
    user_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email 		 VARCHAR(255) NOT NULL,
    login        VARCHAR (255) NOT NULL,
    name  		 VARCHAR(255),
    birthday 	 DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name		 VARCHAR(255) NOT NULL,
    description  VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration 	 INT NOT NULL,
    rating_id	 INT NOT NULL REFERENCES ratings(rating_id),
    rate  INT
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id      INT NOT NULL REFERENCES users(user_id),
    friend_id 	 INT NOT NULL REFERENCES users(user_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    film_id     INT REFERENCES films (film_id),
    genre_id    INT REFERENCES genre (genre_id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS popular_films (
    film_id     BIGINT REFERENCES films (film_id),
    user_id     BIGINT REFERENCES users (user_id),
    PRIMARY KEY (film_id, user_id)

);
